// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcDYNtHr4kPFb40k7QCPEzGiKUN5pJ3g8',
    appId: '1:913989680464:web:27d23d1abeb9fd0db38055',
    messagingSenderId: '913989680464',
    projectId: 'lab345-cff94',
    authDomain: 'lab345-cff94.firebaseapp.com',
    storageBucket: 'lab345-cff94.appspot.com',
    measurementId: 'G-1R7HLT843Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcpaZ69UvmB8wxje-nCXd5WLqDfFbTTmQ',
    appId: '1:913989680464:android:a8fa41834d0fc44cb38055',
    messagingSenderId: '913989680464',
    projectId: 'lab345-cff94',
    storageBucket: 'lab345-cff94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCpzQIwyyc__fchtOrtM7YtorADZpXig0',
    appId: '1:913989680464:ios:0ba852bfdc35f520b38055',
    messagingSenderId: '913989680464',
    projectId: 'lab345-cff94',
    storageBucket: 'lab345-cff94.appspot.com',
    iosBundleId: 'com.example.lab345',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCpzQIwyyc__fchtOrtM7YtorADZpXig0',
    appId: '1:913989680464:ios:102debd51f4f7eedb38055',
    messagingSenderId: '913989680464',
    projectId: 'lab345-cff94',
    storageBucket: 'lab345-cff94.appspot.com',
    iosBundleId: 'com.example.lab345.RunnerTests',
  );
}
